// <auto-generated />
using System;
using Bayan.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Bayan.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260506085918_SyncEFCore10")]
    partial class SyncEFCore10
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bayan.Domain.Entities.DatabaseUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("DatabaseName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("DbUsername")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<string>("EncryptedPassword")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<short>("IsActive")
                        .HasColumnType("NUMBER(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<int>("Port")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(1521);

                    b.Property<int>("ServerType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(0);

                    b.Property<string>("ServiceName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DatabaseUsers", (string)null);
                });

            modelBuilder.Entity("Bayan.Domain.Entities.DynamicQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid?>("DatabaseUserId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<short>("IsEnabled")
                        .HasColumnType("NUMBER(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("SqlQuery")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<int>("TimeoutSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(30);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("DatabaseUserId");

                    b.ToTable("DynamicQueries");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.DynamicQueryDepartment", b =>
                {
                    b.Property<Guid>("DynamicQueryId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Department")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasKey("DynamicQueryId", "Department");

                    b.ToTable("DynamicQueryDepartments");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.DynamicQueryRole", b =>
                {
                    b.Property<Guid>("DynamicQueryId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("DynamicQueryId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("DynamicQueryRoles");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.DynamicQueryUser", b =>
                {
                    b.Property<Guid>("DynamicQueryId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("DynamicQueryId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("DynamicQueryUsers");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.QueryExecutionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("DynamicQueryId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long>("ExecutionDurationMs")
                        .HasColumnType("NUMBER(19)");

                    b.Property<short>("IsSuccess")
                        .HasColumnType("NUMBER(5)");

                    b.Property<string>("OldValuesJson")
                        .HasColumnType("CLOB");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<int>("RowsReturned")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("DynamicQueryId");

                    b.HasIndex("ExecutedAt");

                    b.HasIndex("UserId");

                    b.ToTable("QueryExecutionLogs");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.QueryParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<Guid?>("DropdownQueryId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("DropdownQueryLabelColumn")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("DropdownQueryValueColumn")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<int?>("DropdownSourceType")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("DropdownStaticValues")
                        .HasColumnType("CLOB");

                    b.Property<Guid>("DynamicQueryId")
                        .HasColumnType("RAW(16)");

                    b.Property<short>("IsRequired")
                        .HasColumnType("NUMBER(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<int>("ParameterType")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("DropdownQueryId")
                        .HasDatabaseName("IX_QueryParameters_DropdownQueryId");

                    b.HasIndex("DynamicQueryId");

                    b.ToTable("QueryParameters");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<int>("AuthSource")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Department")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<short>("IsActive")
                        .HasColumnType("NUMBER(5)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("NVARCHAR2(512)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(512)
                        .HasColumnType("NVARCHAR2(512)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.HasIndex("Department");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.UserDatabaseUserAccess", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("DatabaseUserId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("UserId", "DatabaseUserId");

                    b.HasIndex("DatabaseUserId");

                    b.ToTable("UserDatabaseUserAccess", (string)null);
                });

            modelBuilder.Entity("Bayan.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.DynamicQuery", b =>
                {
                    b.HasOne("Bayan.Domain.Entities.DatabaseUser", "DatabaseUser")
                        .WithMany("DynamicQueries")
                        .HasForeignKey("DatabaseUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DatabaseUser");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.DynamicQueryDepartment", b =>
                {
                    b.HasOne("Bayan.Domain.Entities.DynamicQuery", "DynamicQuery")
                        .WithMany("DynamicQueryDepartments")
                        .HasForeignKey("DynamicQueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DynamicQuery");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.DynamicQueryRole", b =>
                {
                    b.HasOne("Bayan.Domain.Entities.DynamicQuery", "DynamicQuery")
                        .WithMany("DynamicQueryRoles")
                        .HasForeignKey("DynamicQueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bayan.Domain.Entities.Role", "Role")
                        .WithMany("DynamicQueryRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DynamicQuery");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.DynamicQueryUser", b =>
                {
                    b.HasOne("Bayan.Domain.Entities.DynamicQuery", "DynamicQuery")
                        .WithMany("DynamicQueryUsers")
                        .HasForeignKey("DynamicQueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bayan.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DynamicQuery");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.QueryExecutionLog", b =>
                {
                    b.HasOne("Bayan.Domain.Entities.DynamicQuery", "DynamicQuery")
                        .WithMany("ExecutionLogs")
                        .HasForeignKey("DynamicQueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bayan.Domain.Entities.User", "User")
                        .WithMany("QueryExecutionLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DynamicQuery");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.QueryParameter", b =>
                {
                    b.HasOne("Bayan.Domain.Entities.DynamicQuery", "DynamicQuery")
                        .WithMany("Parameters")
                        .HasForeignKey("DynamicQueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DynamicQuery");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.UserDatabaseUserAccess", b =>
                {
                    b.HasOne("Bayan.Domain.Entities.DatabaseUser", "DatabaseUser")
                        .WithMany("UserAccess")
                        .HasForeignKey("DatabaseUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bayan.Domain.Entities.User", "User")
                        .WithMany("DatabaseUserAccess")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatabaseUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Bayan.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bayan.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.DatabaseUser", b =>
                {
                    b.Navigation("DynamicQueries");

                    b.Navigation("UserAccess");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.DynamicQuery", b =>
                {
                    b.Navigation("DynamicQueryDepartments");

                    b.Navigation("DynamicQueryRoles");

                    b.Navigation("DynamicQueryUsers");

                    b.Navigation("ExecutionLogs");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.Role", b =>
                {
                    b.Navigation("DynamicQueryRoles");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.User", b =>
                {
                    b.Navigation("DatabaseUserAccess");

                    b.Navigation("QueryExecutionLogs");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
