// <auto-generated />
using System;
using Bayan.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Bayan.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260812060015_AddSystemAuditLog")]
    partial class AddSystemAuditLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bayan.Domain.Entities.DatabaseUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("DatabaseName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("DbUsername")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<string>("EncryptedPassword")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<short>("IsActive")
                        .HasColumnType("NUMBER(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<int>("Port")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(1521);

                    b.Property<int>("ServerType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(0);

                    b.Property<string>("ServiceName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DatabaseUsers", (string)null);
                });

            modelBuilder.Entity("Bayan.Domain.Entities.DatabaseUserRoleAccess", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("DatabaseUserId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("RoleId", "DatabaseUserId");

                    b.HasIndex("DatabaseUserId");

                    b.ToTable("DatabaseUserRoleAccess", (string)null);
                });

            modelBuilder.Entity("Bayan.Domain.Entities.DynamicQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<short>("AllowRunWithoutConfirmation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(5)")
                        .HasDefaultValue((short)1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid?>("DatabaseUserId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<short>("IsEnabled")
                        .HasColumnType("NUMBER(5)");

                    b.Property<short>("IsLongRunning")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(5)")
                        .HasDefaultValue((short)0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<Guid?>("QueryGroupId")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("QueryType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(0);

                    b.Property<short>("SaveOldValues")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(5)")
                        .HasDefaultValue((short)1);

                    b.Property<string>("SqlQuery")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<int>("TimeoutSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(30);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<byte[]>("WordTemplate")
                        .HasColumnType("BLOB");

                    b.Property<string>("WordTemplateFileName")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.HasKey("Id");

                    b.HasIndex("DatabaseUserId");

                    b.HasIndex("QueryGroupId");

                    b.ToTable("DynamicQueries");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.DynamicQueryDepartment", b =>
                {
                    b.Property<Guid>("DynamicQueryId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Department")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasKey("DynamicQueryId", "Department");

                    b.ToTable("DynamicQueryDepartments");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.DynamicQueryRole", b =>
                {
                    b.Property<Guid>("DynamicQueryId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("DynamicQueryId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("DynamicQueryRoles");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.DynamicQueryUser", b =>
                {
                    b.Property<Guid>("DynamicQueryId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("DynamicQueryId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("DynamicQueryUsers");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.QueryExecutionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("DynamicQueryId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long>("ExecutionDurationMs")
                        .HasColumnType("NUMBER(19)");

                    b.Property<short>("IsSuccess")
                        .HasColumnType("NUMBER(5)");

                    b.Property<string>("OldValuesJson")
                        .HasColumnType("CLOB");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<int>("RowsReturned")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("DynamicQueryId");

                    b.HasIndex("ExecutedAt");

                    b.HasIndex("UserId");

                    b.ToTable("QueryExecutionLogs");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.QueryGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("QueryGroups");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.QueryGroupDepartment", b =>
                {
                    b.Property<Guid>("QueryGroupId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Department")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasKey("QueryGroupId", "Department");

                    b.ToTable("QueryGroupDepartments");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.QueryGroupRole", b =>
                {
                    b.Property<Guid>("QueryGroupId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("QueryGroupId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("QueryGroupRoles");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.QueryGroupUser", b =>
                {
                    b.Property<Guid>("QueryGroupId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("QueryGroupId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("QueryGroupUsers");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.QueryParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<short>("AllowMultiple")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<Guid?>("DropdownQueryId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("DropdownQueryLabelColumn")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("DropdownQueryValueColumn")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<int?>("DropdownSourceType")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("DropdownStaticValues")
                        .HasColumnType("CLOB");

                    b.Property<Guid>("DynamicQueryId")
                        .HasColumnType("RAW(16)");

                    b.Property<short>("IsRequired")
                        .HasColumnType("NUMBER(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<int>("ParameterType")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("DropdownQueryId")
                        .HasDatabaseName("IX_QueryParameters_DropdownQueryId");

                    b.HasIndex("DynamicQueryId");

                    b.ToTable("QueryParameters");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.ScheduledTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("ArchiveFolder")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<short>("CombineOutput")
                        .HasColumnType("NUMBER(5)");

                    b.Property<short>("CombinedAppendTimestamp")
                        .HasColumnType("NUMBER(5)");

                    b.Property<string>("CombinedCsvSeparator")
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)");

                    b.Property<string>("CombinedFileName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<int>("CombinedFormat")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<short>("IncludeHeaders")
                        .HasColumnType("NUMBER(5)");

                    b.Property<short>("IsEnabled")
                        .HasColumnType("NUMBER(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<DateTime?>("NextRunAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("OutputFolder")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("TimestampFormat")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("NextRunAt");

                    b.ToTable("ScheduledTasks");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.ScheduledTaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<short>("AppendTimestamp")
                        .HasColumnType("NUMBER(5)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CsvSeparator")
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)");

                    b.Property<Guid>("DynamicQueryId")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("ExportFormat")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("FileNamePrefix")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("InitialKey")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("KeyColumn")
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<string>("KeyParameter")
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<string>("LastKeyValue")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("ParametersJson")
                        .HasColumnType("CLOB");

                    b.Property<Guid>("ScheduledTaskId")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("DynamicQueryId");

                    b.HasIndex("ScheduledTaskId");

                    b.ToTable("ScheduledTaskItems");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.ScheduledTaskRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ItemResultsJson")
                        .HasColumnType("CLOB");

                    b.Property<Guid>("ScheduledTaskId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<Guid?>("TriggeredByUserId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("TriggeredByUsername")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledTaskId");

                    b.HasIndex("StartedAt");

                    b.ToTable("ScheduledTaskRuns");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.ScheduledTaskTrigger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("DayOfMonth")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Frequency")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("IntervalMinutes")
                        .HasColumnType("NUMBER(10)");

                    b.Property<Guid>("ScheduledTaskId")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TimeOfDay")
                        .HasMaxLength(5)
                        .HasColumnType("NVARCHAR2(5)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledTaskId");

                    b.ToTable("ScheduledTaskTriggers");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.ScheduledTaskViewer", b =>
                {
                    b.Property<Guid>("ScheduledTaskId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.Property<short>("CanDownloadFiles")
                        .HasColumnType("NUMBER(5)");

                    b.HasKey("ScheduledTaskId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ScheduledTaskViewers");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.SystemAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("DetailsJson")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("EntityName")
                        .HasMaxLength(400)
                        .HasColumnType("NVARCHAR2(400)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)");

                    b.Property<short>("IsSuccess")
                        .HasColumnType("NUMBER(5)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("UserId");

                    b.ToTable("SystemAuditLogs");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.SystemTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemTemplates");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<int>("AuthSource")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Department")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<short>("IsActive")
                        .HasColumnType("NUMBER(5)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("NVARCHAR2(512)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(512)
                        .HasColumnType("NVARCHAR2(512)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.HasIndex("Department");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"Email\" IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.DatabaseUserRoleAccess", b =>
                {
                    b.HasOne("Bayan.Domain.Entities.DatabaseUser", "DatabaseUser")
                        .WithMany("RoleAccess")
                        .HasForeignKey("DatabaseUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bayan.Domain.Entities.Role", "Role")
                        .WithMany("DatabaseUserAccess")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatabaseUser");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.DynamicQuery", b =>
                {
                    b.HasOne("Bayan.Domain.Entities.DatabaseUser", "DatabaseUser")
                        .WithMany("DynamicQueries")
                        .HasForeignKey("DatabaseUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Bayan.Domain.Entities.QueryGroup", "QueryGroup")
                        .WithMany("DynamicQueries")
                        .HasForeignKey("QueryGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DatabaseUser");

                    b.Navigation("QueryGroup");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.DynamicQueryDepartment", b =>
                {
                    b.HasOne("Bayan.Domain.Entities.DynamicQuery", "DynamicQuery")
                        .WithMany("DynamicQueryDepartments")
                        .HasForeignKey("DynamicQueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DynamicQuery");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.DynamicQueryRole", b =>
                {
                    b.HasOne("Bayan.Domain.Entities.DynamicQuery", "DynamicQuery")
                        .WithMany("DynamicQueryRoles")
                        .HasForeignKey("DynamicQueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bayan.Domain.Entities.Role", "Role")
                        .WithMany("DynamicQueryRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DynamicQuery");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.DynamicQueryUser", b =>
                {
                    b.HasOne("Bayan.Domain.Entities.DynamicQuery", "DynamicQuery")
                        .WithMany("DynamicQueryUsers")
                        .HasForeignKey("DynamicQueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bayan.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DynamicQuery");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.QueryExecutionLog", b =>
                {
                    b.HasOne("Bayan.Domain.Entities.DynamicQuery", "DynamicQuery")
                        .WithMany("ExecutionLogs")
                        .HasForeignKey("DynamicQueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bayan.Domain.Entities.User", "User")
                        .WithMany("QueryExecutionLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DynamicQuery");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.QueryGroupDepartment", b =>
                {
                    b.HasOne("Bayan.Domain.Entities.QueryGroup", "QueryGroup")
                        .WithMany("QueryGroupDepartments")
                        .HasForeignKey("QueryGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QueryGroup");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.QueryGroupRole", b =>
                {
                    b.HasOne("Bayan.Domain.Entities.QueryGroup", "QueryGroup")
                        .WithMany("QueryGroupRoles")
                        .HasForeignKey("QueryGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bayan.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QueryGroup");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.QueryGroupUser", b =>
                {
                    b.HasOne("Bayan.Domain.Entities.QueryGroup", "QueryGroup")
                        .WithMany("QueryGroupUsers")
                        .HasForeignKey("QueryGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bayan.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QueryGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.QueryParameter", b =>
                {
                    b.HasOne("Bayan.Domain.Entities.DynamicQuery", "DynamicQuery")
                        .WithMany("Parameters")
                        .HasForeignKey("DynamicQueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DynamicQuery");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.ScheduledTaskItem", b =>
                {
                    b.HasOne("Bayan.Domain.Entities.DynamicQuery", "DynamicQuery")
                        .WithMany()
                        .HasForeignKey("DynamicQueryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Bayan.Domain.Entities.ScheduledTask", "ScheduledTask")
                        .WithMany("Items")
                        .HasForeignKey("ScheduledTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DynamicQuery");

                    b.Navigation("ScheduledTask");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.ScheduledTaskRun", b =>
                {
                    b.HasOne("Bayan.Domain.Entities.ScheduledTask", "ScheduledTask")
                        .WithMany("Runs")
                        .HasForeignKey("ScheduledTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduledTask");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.ScheduledTaskTrigger", b =>
                {
                    b.HasOne("Bayan.Domain.Entities.ScheduledTask", "ScheduledTask")
                        .WithMany("Triggers")
                        .HasForeignKey("ScheduledTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduledTask");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.ScheduledTaskViewer", b =>
                {
                    b.HasOne("Bayan.Domain.Entities.ScheduledTask", "ScheduledTask")
                        .WithMany("Viewers")
                        .HasForeignKey("ScheduledTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bayan.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduledTask");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Bayan.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bayan.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.DatabaseUser", b =>
                {
                    b.Navigation("DynamicQueries");

                    b.Navigation("RoleAccess");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.DynamicQuery", b =>
                {
                    b.Navigation("DynamicQueryDepartments");

                    b.Navigation("DynamicQueryRoles");

                    b.Navigation("DynamicQueryUsers");

                    b.Navigation("ExecutionLogs");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.QueryGroup", b =>
                {
                    b.Navigation("DynamicQueries");

                    b.Navigation("QueryGroupDepartments");

                    b.Navigation("QueryGroupRoles");

                    b.Navigation("QueryGroupUsers");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.Role", b =>
                {
                    b.Navigation("DatabaseUserAccess");

                    b.Navigation("DynamicQueryRoles");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.ScheduledTask", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Runs");

                    b.Navigation("Triggers");

                    b.Navigation("Viewers");
                });

            modelBuilder.Entity("Bayan.Domain.Entities.User", b =>
                {
                    b.Navigation("QueryExecutionLogs");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
