// <auto-generated />
using System;
using DotNetDBTasks.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNetDBTasks.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260220000000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("DotNetDBTasks.Domain.Entities.DynamicQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("SqlQuery")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("NVARCHAR2(4000)");

                    b.Property<int>("TimeoutSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(30);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.ToTable("DynamicQueries");
                });

            modelBuilder.Entity("DotNetDBTasks.Domain.Entities.DynamicQueryRole", b =>
                {
                    b.Property<Guid>("DynamicQueryId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("DynamicQueryId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("DynamicQueryRoles");
                });

            modelBuilder.Entity("DotNetDBTasks.Domain.Entities.QueryExecutionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("DynamicQueryId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long>("ExecutionDurationMs")
                        .HasColumnType("NUMBER(19)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("NVARCHAR2(4000)");

                    b.Property<int>("RowsReturned")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("DynamicQueryId");

                    b.HasIndex("ExecutedAt");

                    b.HasIndex("UserId");

                    b.ToTable("QueryExecutionLogs");
                });

            modelBuilder.Entity("DotNetDBTasks.Domain.Entities.QueryParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<Guid>("DynamicQueryId")
                        .HasColumnType("RAW(16)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<int>("ParameterType")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("DynamicQueryId");

                    b.ToTable("QueryParameters");
                });

            modelBuilder.Entity("DotNetDBTasks.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DotNetDBTasks.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("NVARCHAR2(512)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(512)
                        .HasColumnType("NVARCHAR2(512)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DotNetDBTasks.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("DotNetDBTasks.Domain.Entities.DynamicQueryRole", b =>
                {
                    b.HasOne("DotNetDBTasks.Domain.Entities.DynamicQuery", "DynamicQuery")
                        .WithMany("DynamicQueryRoles")
                        .HasForeignKey("DynamicQueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNetDBTasks.Domain.Entities.Role", "Role")
                        .WithMany("DynamicQueryRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DynamicQuery");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DotNetDBTasks.Domain.Entities.QueryExecutionLog", b =>
                {
                    b.HasOne("DotNetDBTasks.Domain.Entities.DynamicQuery", "DynamicQuery")
                        .WithMany("ExecutionLogs")
                        .HasForeignKey("DynamicQueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNetDBTasks.Domain.Entities.User", "User")
                        .WithMany("QueryExecutionLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DynamicQuery");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DotNetDBTasks.Domain.Entities.QueryParameter", b =>
                {
                    b.HasOne("DotNetDBTasks.Domain.Entities.DynamicQuery", "DynamicQuery")
                        .WithMany("Parameters")
                        .HasForeignKey("DynamicQueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DynamicQuery");
                });

            modelBuilder.Entity("DotNetDBTasks.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("DotNetDBTasks.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNetDBTasks.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DotNetDBTasks.Domain.Entities.DynamicQuery", b =>
                {
                    b.Navigation("DynamicQueryRoles");

                    b.Navigation("ExecutionLogs");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("DotNetDBTasks.Domain.Entities.Role", b =>
                {
                    b.Navigation("DynamicQueryRoles");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DotNetDBTasks.Domain.Entities.User", b =>
                {
                    b.Navigation("QueryExecutionLogs");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
